name: Build Web

on:
  push:
    branches: [ master ]
    paths:
      - src/**

jobs:
  build:
    runs-on: self-hosted
    env:
      CI: ''
    
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo $CI
      - run: npm install
      - run: npm run build
  deploy:
    needs: [build]
    runs-on: self-hosted
    steps:
      - run: scp -r ./build/ ${{ secrets.SSH_DEPLOY_HOST }}:/var/www/html/orbit.novastudios.uk
